### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by Leooo** [yapplabs/ember-wormhole#88]
Hello,

We have quite a lot of memory leak in our Ember acceptance tests and are trying to identify where it comes from.

We use ember-wormhole at different places in our app. Doing a javascript heap snapshot shows multiple detached nodes coming from ember-wormhole. Hard to know the exact place where the mem is not released, but by grepping what I see in the snapshot it seems like there are still references to the destroyed ember-wormhole components coming from the CachedReference of the dom (see keywords `_lastValue` and `_wormholeTailNode` below).

May that be because when destroying the app at the end of our acceptance tests we don't release all mem contained in the `destination` id ??

Any help very welcome,

Thanks,

L
![screenshot 2017-02-19 15 20 25 2](https://cloud.githubusercontent.com/assets/2422936/23103685/f7479522-f6b6-11e6-9219-f47218d43038.png)

**Comment by krisselden** [comment]
@Leooo The destination would need a reference back to the wormhole instance, the only way that would happen via an event listener you have not torn down when the app is destroyed.

You need to expand down to the GC root, it is below env in this.  This used to auto expand, but since they added weak references and internal v8 structures that are GCed this stopped work, you now have to find a "strong" path to a GC root yourself, this can be really difficult because it also doesn't filter out cycles from the view.

I think DevTools needs to updated to make this more doable as right now this view has become borderline unusable.

**Comment by Leooo** [comment]
@krisselden, tried to take another heap snapshot and can't reproduce. It may be because I'm now using an ember-gesture forked version containing a bug fix. Closing the issue.
